Repository VinhVTHE181750/mJOB, pull requests merged in 2024-07, with the labels that each got.

#106 ConfirmJob and update jobs.js, JobDetail
  client/src/App.jsx
  client/src/pages/jobs/ConfirmJob.jsx
  client/src/pages/jobs/JobDetail.jsx
  server/package-lock.json
  server/package.json
  server/src/routes/jobs.js
Labels: addition, change, fix

#107 Input validators
  server/config.json
  server/server.js
  server/src/routes/test.js
  server/src/utils/CreditCard.js
  server/src/utils/PhoneNumberProvider.js
  server/src/validators/CreditCardValidator.js
  server/src/validators/NumberValidator.js
  server/src/validators/StringBlacklist.js
  server/src/validators/StringValidator.js
  server/validate.json
Labels: add, required, help needed

#112 Db update + JWT implementation
  client/src/components/forum/AddForm.jsx
  client/src/components/forum/EditForm.jsx
  client/src/components/forum/ListComment.jsx
  client/src/components/forum/ListPost.jsx
  client/src/components/forum/Post.jsx
  client/src/components/forum/PostCard.jsx
  client/src/components/forum/PostSearch.jsx
  client/src/hooks/forum/categories/useCategories.js
  client/src/hooks/forum/comments/useCommentsQuery.js
  client/src/hooks/forum/posts/usePostDelete.js
  client/src/hooks/forum/posts/usePostDetail.js
  client/src/hooks/forum/posts/usePostInsert.js
  client/src/hooks/forum/posts/usePostUpdate.js
  client/src/hooks/forum/posts/usePostsQuery.js
  client/src/pages/forum/EditPost.jsx
  client/src/pages/forum/Forum.jsx
  client/src/pages/forum/PostDetail.jsx
  server/config.json
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/models/Auth.js
  server/src/models/User.js
  server/src/routes/Forum.js
  server/src/routes/auth.js
  server/src/routes/forum/Metrics.js
  server/src/routes/forum/Post.js
  server/src/routes/forum/comment/Get.js
  server/src/routes/forum/comment/Post.js
  server/src/routes/forum/post/Delete.js
  server/src/routes/forum/post/Get.js
  server/src/routes/forum/post/Post.js
  server/src/routes/forum/post/Put.js
  server/src/routes/test.js
  server/src/utils/JWT.js
Labels: add, change, fix

#116 AppyJob, ActiveJob, ActiveJobDetail
  client/src/App.jsx
  client/src/assets/css/EnlistJob.css
  client/src/pages/jobs/ActiveJob.jsx
  client/src/pages/jobs/AppliedJob.jsx
  client/src/pages/jobs/AppliedJobDetail.jsx
  client/src/pages/jobs/ApplyJob.jsx
  client/src/pages/jobs/CreatedJobDetail.jsx
  client/src/pages/jobs/CreatedJobs.jsx
  client/src/pages/jobs/EditJob.jsx
  client/src/pages/jobs/EnlistJob.jsx
  client/src/pages/jobs/JobDetail.jsx
  server/scripts/DB/Job.sql
  server/src/routes/jobs.js
Labels: add

#120 Fix total user count in admin dashboard
  .idea/rcb-settings.xml
  client/src/App.jsx
  client/src/assets/img/apply.jpg
  client/src/hooks/useCountUser.js
  client/src/pages/home/Dashboard.jsx
  client/src/pages/jobs/ApplyJob.jsx
  client/src/pages/profile/Profile.jsx
  server/.idea/.gitignore
  server/.idea/modules.xml
  server/.idea/server.iml
  server/.idea/vcs.xml
  server/package-lock.json
  server/server.js
  server/src/routes/dashboard/countTotalUser.js
Labels: change, fix

#123 Add pseudo payment routes
  server/src/models/User.js
  server/src/models/payment/Balance.js
  server/src/routes/Payment.js
  server/src/routes/forum/Comment.js
  server/src/routes/index.js
  server/src/routes/payment/Balance.js
  server/src/routes/payment/Deposit.js
  server/src/routes/payment/Transfer.js
  server/src/routes/payment/Withdraw.js
Labels: add

#130 Job
  client/src/pages/jobs/AppliedJob.jsx
  client/src/pages/jobs/CreatedJobs.jsx
  client/src/pages/jobs/EditJob.jsx
  server/scripts/DB/Job.sql
  server/src/routes/jobs.js
Labels: add, change

#131 Sequelize job
  server/src/models/job/Application.js
  server/src/models/job/Compensation.js
  server/src/models/job/Job.js
  server/src/models/job/JobHistory.js
  server/src/models/job/Requirement.js
  server/src/models/job/RequirementStorage.js
  server/src/routes/Job.js
  server/src/routes/index.js
  server/src/routes/job/Jobs.js
Labels: change

#133 Login update
  client/src/components/Navbar.jsx
  client/src/components/forum/EditForm.jsx
  client/src/context/AuthContext.jsx
  client/src/functions/httpService.js
  client/src/hooks/forum/posts/usePostDelete.js
  client/src/hooks/forum/posts/usePostDetail.js
  client/src/hooks/forum/posts/usePostInsert.js
  client/src/hooks/forum/posts/usePostsQuery.js
  client/src/hooks/forum/posts/useViewCount.js
  client/src/hooks/useLoginQuery.js
  client/src/pages/auth/Login.jsx
  server/src/middlewares.js
  server/src/routes/forum/post/Post.js
Labels: fix

#132 Forum update
  client/src/App.jsx
  client/src/assets/css/Forum.css
  client/src/components/forum/AddForm.jsx
  client/src/components/forum/EditForm.jsx
  client/src/components/forum/ListPost.jsx
  client/src/components/forum/Post.jsx
  client/src/components/forum/PostCard.jsx
  client/src/components/forum/PostSearch.jsx
  client/src/components/forum/micro/Category.jsx
  client/src/components/forum/micro/InteractionCount.jsx
  client/src/components/forum/micro/Tag.jsx
  client/src/components/ui/buttons/NavigateButton.jsx
  client/src/context/ForumContext.jsx
  client/src/hooks/forum/likes/useLikesQuery.js
  client/src/hooks/forum/posts/usePostDetail.js
  client/src/hooks/forum/useWebSocket.js
  client/src/pages/forum/Forum.jsx
  client/src/pages/forum/ManageCategories.jsx
  client/src/socket/index.js
  client/src/store/reducers/forum/commentsReducer.js
  client/src/store/reducers/forum/likesReducer.js
  client/src/store/reducers/forum/postCategoriesReducer.js
  client/src/store/reducers/forum/postReducer.js
  client/src/store/reducers/forum/postsReducer.js
  client/src/store/reducers/forum/viewsReducer.js
  client/src/store/reducers/global/userReducer.js
  client/src/store/store.js
  server/io.js
  server/src/models/forum/metric/PostMetric.js
  server/src/routes/forum/Comment.js
  server/src/routes/forum/Like.js
  server/src/routes/forum/comment/Get.js
  server/src/routes/forum/post/Delete.js
  server/src/routes/forum/post/Get.js
  server/src/routes/forum/post/Post.js
  server/src/routes/forum/post/Put.js
Labels: change, fix

#136 Authentication
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Navbar.jsx
  client/src/context/UserContext.jsx
  client/src/hooks/useLoginQuery.js
  client/src/pages/auth/Logout.jsx
  server/src/routes/auth.js
Labels: change, fix

#140 Fix Job
  client/src/pages/jobs/AppliedJob.jsx
  client/src/pages/jobs/CreatedJobs.jsx
  client/src/pages/jobs/EditJob.jsx
  server/src/models/job/Application.js
  server/src/models/job/Compensation.js
  server/src/models/job/Job.js
  server/src/models/job/JobHistory.js
  server/src/models/job/Requirement.js
  server/src/models/job/RequirementStorage.js
  server/src/routes/Job.js
  server/src/routes/dashboard/countTotalUser.js
  server/src/routes/index.js
  server/src/routes/job/Jobs.js
  server/src/routes/jobs.js
Labels: fix

#142 Fix build error and update auth
  client/src/App.jsx
  client/src/components/Navbar.jsx
  client/src/components/forum/AddForm.jsx
  client/src/components/forum/EditForm.jsx
  client/src/components/forum/Post.jsx
  client/src/components/forum/PostCard.jsx
  client/src/context/AuthContext.jsx
  client/src/context/ForumContext.jsx
  client/src/context/UserContext.jsx
  client/src/hooks/forum/likes/useIsLiked.js
  client/src/hooks/forum/likes/useLikesQuery.js
  client/src/hooks/forum/likes/useLikesUpdate.js
  client/src/hooks/forum/posts/usePostDetail.js
  client/src/hooks/forum/posts/usePostUpdate.js
  client/src/hooks/useLoginQuery.js
  client/src/pages/forum/ManageCategories.jsx
  server/src/middlewares.js
  server/src/routes/forum/post/Post.js
  server/src/routes/forum/post/Put.js
  server/src/utils/Interceptor.js
  setup.bat
Labels: fix

#144 DB update
  client/src/App.jsx
  client/src/components/forum/AddForm.jsx
  client/src/components/forum/PostSearch.jsx
  client/src/hooks/user/useWhoAmI.js
  client/src/pages/auth/Login.jsx
  client/src/pages/error/ToLogin.jsx
  client/src/pages/forum/Forum.jsx
  client/src/pages/forum/ManageCategories.jsx
  client/src/pages/payment/PaymentHistory.jsx
  server/config.json
  server/scripts/Diagrams/July17 Diagram-min.jpg
  server/scripts/Diagrams/July17 Diagram.jpg
  server/scripts/Versions/July 16.sql
  server/src/models/forum/metric/CategoryMetric.js
  server/src/models/forum/metric/CommentMetric.js
  server/src/models/forum/metric/ForumMetric.js
  server/src/models/forum/metric/PostMetric.js
  server/src/models/forum/metric/PublicChatMetric.js
  server/src/models/forum/metric/TagMetric.js
  server/src/models/forum/post/PostHistory.js
  server/src/models/user/ForumMetric.js
  server/src/models/user/User.js
  server/src/routes/User.js
  server/src/routes/WhoAmI.js
  server/src/routes/forum/Metrics.js
  server/src/routes/forum/post/Get.js
  server/src/routes/forum/post/Post.js
  server/src/routes/forum/post/Put.js
  server/src/routes/index.js
Labels: add, change

#149 Forum update
  client/src/App.jsx
  client/src/components/forum/PostSearch.jsx
  client/src/hooks/user/useWhoAmI.js
  client/src/pages/forum/Forum.jsx
  client/src/pages/forum/ManageCategories.jsx
  client/src/pages/payment/ContinuePayment.jsx
  client/src/pages/payment/Deposit.jsx
  client/src/pages/payment/DepositBalance.jsx
  client/src/pages/payment/PaymentHistory.jsx
  client/src/pages/payment/PaymentPortal.jsx
  client/src/pages/payment/micro/StatusBadge.jsx
  server/src/models/support/FAQ.js
  server/src/models/support/Ticket.js
Labels: add

#148 Update UI HomeUser
  client/src/App.jsx
  client/src/assets/css/HomeUser.css
  client/src/assets/css/JobsStatistic.css
  client/src/assets/css/Navbar.css
  client/src/assets/css/PostStatistic.css
  client/src/components/home/HomeNavbar.jsx
  client/src/components/home/JobsStatistic.jsx
  client/src/components/home/PostStatistic.jsx
  client/src/pages/home/HomeUser.jsx
Labels: change

#150 Deployment check on new PR
  .github/workflows/BuildReactJS.yml
Labels: other

#157 Update Profile and related pages
  client/src/App.jsx
  client/src/pages/home/Dashboard.jsx
  client/src/pages/home/Jobs.jsx
  client/src/pages/home/Users.jsx
  client/src/pages/profile/EditProfile.jsx
  client/src/pages/profile/Profile.jsx
  client/src/pages/profile/WorkExperience.jsx
  client/src/pages/technical/Settings.jsx
  server/src/routes/Profile.js
  server/src/routes/dashboard/jobManager.js
  server/src/routes/index.js
Labels: add

#159 Register balance faq report
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Navbar.jsx
  client/src/context/UserContext.jsx
  client/src/main.jsx
  client/src/pages/auth/Login.jsx
  client/src/pages/auth/Register.jsx
  client/src/pages/auth/ResetPassword.jsx
  client/src/pages/balance/drawBalance.jsx
  client/src/pages/faq/Faq.jsx
  client/src/pages/report/report.jsx
  server/config.json
  server/package-lock.json
  server/package.json
  server/src/helper/sendmail.js
  server/src/routes/Payment.js
  server/src/routes/auth.js
  server/src/routes/faq.js
  server/src/routes/index.js
  server/src/routes/ticket.js
Labels: add

#164 Remove package-lock.json (s) and update forum
  .gitignore
  client/package-lock.json
  client/src/pages/payment/PaymentHistory.jsx
  client/src/pages/payment/PaymentPortal.jsx
  server/package-lock.json
  server/src/models/forum/metric/ForumMetric.js
  server/src/models/job/Job.js
  server/src/models/user/User.js
  server/src/routes/job/Jobs.js
  server/src/routes/payment/Balance.js
Labels: remove, change

#163 Profile edit
  client/src/App.jsx
  client/src/assets/css/HomeUser.css
  client/src/assets/css/JobsStatistic.css
  client/src/assets/css/Navbar.css
  client/src/assets/css/PostStatistic.css
  client/src/components/Navbar.jsx
  client/src/components/home/HomeCarousel.jsx
  client/src/components/home/HomeNavbar.jsx
  client/src/components/home/HotJobs.jsx
  client/src/components/home/HotNew.jsx
  client/src/components/home/JobsStatistic.jsx
  client/src/components/home/PostStatistic.jsx
  client/src/components/job/JobList.jsx
  client/src/components/job/SideBar.jsx
  client/src/hooks/home/useHotPosts.js
  client/src/hooks/home/useNewPosts.js
  client/src/hooks/home/useOngoingJobs.js
  client/src/hooks/home/usePendingJobs.js
  client/src/hooks/home/useRelatedJobs.js
  client/src/hooks/useTop3Jobs.js
  client/src/pages/home/HomeGuest.jsx
  client/src/pages/home/HomePage.jsx
  client/src/pages/home/HomeUser.jsx
  client/src/pages/home/Jobs.jsx
  client/src/pages/home/Users.jsx
  client/src/pages/profile/EditProfile.jsx
  client/src/pages/profile/Profile.jsx
  client/src/pages/profile/WorkExperience.jsx
  client/src/pages/technical/Settings.jsx
  server/src/routes/HomeUser.js
  server/src/routes/WorkExperience.js
  server/src/routes/index.js
Labels: add, change, fix

#173 Fix #168
  client/src/components/forum/micro/LikeButton.jsx
  server/src/routes/forum/Like.js
  server/src/routes/forum/post/Get.js
  server/src/utils/JWT.js
Labels: fix

#174 Fix #171
  server/src/utils/JWT.js
Labels: fix

#178 Forum update
  client/src/components/forum/AddForm.jsx
  client/src/components/forum/Comment.jsx
  client/src/components/forum/Post.jsx
  client/src/components/forum/PostCard.jsx
  client/src/components/forum/micro/LikeButton.jsx
  client/src/hooks/forum/posts/usePostInsert.js
  client/src/pages/forum/AddPost.jsx
  client/src/pages/forum/EditPost.jsx
  client/src/pages/forum/ManageCategories.jsx
  client/src/pages/forum/PostDetail.jsx
  server/src/models/forum/comment/Comment.js
  server/src/models/forum/post/Post.js
  server/src/models/forum/post/PostHistory.js
  server/src/routes/forum/Category.js
  server/src/routes/forum/Like.js
  server/src/routes/forum/post/Get.js
  server/src/routes/forum/post/Post.js
Labels: fix, Forum

#182 Update New Database Version Part 1
  client/src/App.jsx
  client/src/assets/css/HomeUser.css
  client/src/assets/css/JobsStatistic.css
  client/src/assets/css/Navbar.css
  client/src/assets/css/PostStatistic.css
  client/src/components/home/HomeCarousel.jsx
  client/src/components/home/HomeNavbar.jsx
  client/src/components/home/HotJobs.jsx
  client/src/components/home/HotNew.jsx
  client/src/components/home/JobsStatistic.jsx
  client/src/components/home/PostStatistic.jsx
  client/src/hooks/home/homeguest/useMarketingContent.js
  client/src/hooks/home/useHotPosts.js
  client/src/hooks/home/useNewPosts.js
  client/src/hooks/home/useOngoingJobs.js
  client/src/hooks/home/usePendingJobs.js
  client/src/hooks/home/useRelatedJobs.js
  client/src/pages/home/HomeUser.jsx
  server/src/models/home/marketing.js
  server/src/models/job/Job.js
  server/src/models/job/JobMetric.js
  server/src/routes/HomeGuest.js
  server/src/routes/HomeUser.js
  server/src/routes/JobList.js
  server/src/routes/home/HomeGuest.js
  server/src/routes/home/HomeUser.js
  server/src/routes/index.js
  server/src/routes/jobDashBoard/dashboard.js
  server/src/routes/joblist/JobList.js
Labels: add, change, other, Jobs

#183 Navbar update
  client/index.html
  client/logo.png
  client/src/App.jsx
  client/src/assets/css/Navbar.css
  client/src/components/HomeNavbar.jsx
  client/src/components/Navbar.jsx
  client/src/components/home/HomeNavbar.jsx
  logo/Untitled.png
Labels: fix

#207 Update navbar and some strings
  client/src/components/forum/PostSearch.jsx
  client/src/components/home/HomeNavbar.jsx
  client/src/pages/auth/Register.jsx
  client/src/pages/auth/ResetPassword.jsx
  client/src/pages/jobs/Market.jsx
  server/src/models/user/User.js
Labels: change

#208 Forum update
  client/src/App.jsx
  client/src/pages/payment/PaymentPortal.jsx
Labels: fix, Payment

#212 Update Ticket.js
  server/src/models/user/Ticket.js
Labels: change

#214 Content suggestion logic for Jobs
  server/src/models/user/JobPreference.js
  server/src/models/user/PostPreference.js
  server/src/models/user/User.js
  server/src/routes/index.js
  server/src/routes/test.js
  server/src/utils/algorithms/RelativeSearch.js
Labels: add

#220 Content suggestion logic
  server/src/models/job/Application.js
  server/src/models/job/Job.js
  server/src/utils/algorithms/RelativeSearch.js
Labels: add, Forum, Jobs

#222 EditJob, EnlistJob and JobDetail
  client/src/components/Navbar.jsx
  client/src/hooks/useCountJob.js
  client/src/pages/home/Dashboard.jsx
  client/src/pages/home/Jobs.jsx
  client/src/pages/home/Users.jsx
  client/src/pages/jobs/ApplyJob.jsx
  client/src/pages/jobs/EditJob.jsx
  client/src/pages/jobs/EnlistJob.jsx
  client/src/pages/jobs/JobDetail.jsx
  client/src/pages/profile/EditProfile.jsx
  client/src/pages/profile/Profile.jsx
  client/src/pages/profile/WorkExperience.jsx
  client/src/pages/technical/Settings.jsx
  package-lock.json
  server/src/models/job/Job.js
  server/src/routes/Profile.js
  server/src/routes/WhoAmI.js
  server/src/routes/dashboard/jobManager.js
  server/src/routes/dashboard/userManager.js
  server/src/routes/job/Jobs.js
Labels: change, fix

#224 OpenAI integration
  server/config.json
  server/package.json
  server/src/routes/test.js
  server/src/utils/OpenAI.js
Labels: add, Forum, Jobs

#228 Finish deposit page with minimal UI
  client/package.json
  client/src/App.jsx
  client/src/components/payment/PayPalComponent.jsx
  client/src/pages/payment/Deposit.jsx
  client/src/pages/payment/PaymentHistory.jsx
  client/src/pages/payment/PaymentPortal.jsx
  server/config.json
  server/src/routes/Payment.js
  server/src/routes/payment/PayPal.js
Labels: add, Payment

#229 Job
  client/src/App.jsx
  client/src/components/job/ApplicationList.jsx
  client/src/components/job/SideBar.jsx
  client/src/hooks/job/dashboard/useApplyList.js
  client/src/pages/jobs/ApplyJob.jsx
  client/src/pages/jobs/ConfirmJob.jsx
  client/src/pages/jobs/CreatedJobDetail.jsx
  client/src/pages/jobs/CreatedJobs.jsx
  client/src/pages/jobs/JobDetail.jsx
  server/src/models/job/Application.js
  server/src/routes/Dashboard.js
  server/src/routes/job/Jobs.js
Labels: Jobs

#234 Forum moderation #1
  client/src/App.jsx
  client/src/components/TestData.jsx
  client/src/components/forum/Comment.jsx
  client/src/components/forum/Insights.jsx
  client/src/components/forum/ListPost.jsx
  client/src/components/forum/Post.jsx
  client/src/components/home/HomeNavbar.jsx
  client/src/pages/forum/Forum.jsx
  client/src/pages/forum/Insights.jsx
  client/src/pages/forum/PostDetail.jsx
  server/src/models/support/Ticket.js
  server/src/models/user/Ticket.js
Labels: add, Forum

#235 Update User model to include CVs
  client/src/components/forum/Insights.jsx
  client/src/components/forum/ListPost.jsx
  server/src/models/user/User.js
Labels: change, Profile
