Repository VinhVTHE181750/mJOB, pull requests merged in 2024-06, with the labels that each got.

#26 Update backend API routes
  .gitignore
  backend/server.js
  backend/src/models/DBContext.js
  backend/src/routes/____.js
  backend/src/routes/auth.js
  backend/src/routes/datapost.js
  backend/src/routes/marketing.js
  backend/src/routes/posts.js
Labels: enhancement

#27 Update DB.sql
  backend/scripts/DB.sql
Labels: enhancement

#28 Add backend\server.json
  .gitignore
  backend/config/server.json
  backend/scripts/db draft.txt
Labels: enhancement

#40 Minor changes
  backend/server.js
  backend/src/routes/posts.js
  frontend/src/App.jsx
  frontend/src/pages/auth/ResetPassword.jsx
  frontend/src/pages/forum/Forum.jsx
  frontend/src/pages/home/Dashboard.jsx
  frontend/src/pages/technical/AdminDashboard.jsx
Labels: change

#44 EnlistJob
  frontend/src/App.jsx
  frontend/src/assets/css/EnlistJob.css
  frontend/src/assets/img/Stole.jpg
  frontend/src/pages/jobs/Addjob.jsx
  frontend/src/pages/jobs/EnlistJob.jsx
Labels: addition, change

#47 Forum update and some minor changes
  backend/config/server.json
  backend/package-lock.json
  backend/package.json
  backend/scripts/DB.sql
  backend/scripts/Sample.sql
  backend/src/routes/auth.js
  backend/src/routes/posts.js
  frontend/src/App.jsx
  frontend/src/components/forum/ListPost.jsx
  frontend/src/context/AuthProvider.jsx
  frontend/src/hooks/useLoginQuery.js
  frontend/src/hooks/usePostUpdate.js
  frontend/src/pages/auth/Login.jsx
  frontend/src/pages/auth/Register.jsx
  frontend/src/pages/forum/EditPost.jsx
  frontend/src/pages/forum/PostDetail.jsx
Labels: addition, change

#48 Admin dashboard prototype
  backend/config/db.json
  backend/scripts/DB.sql
  backend/scripts/Sample.sql
  backend/server.js
  backend/src/routes/dashboard/countActiveUser.js
  backend/src/routes/dashboard/countTotalUser.js
  backend/src/routes/userCount.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/hooks/useCountUser.js
  frontend/src/pages/home/Dashboard.jsx
  frontend/src/pages/home/HomeAdmin.jsx
  frontend/src/pages/home/Jobs.jsx
  frontend/src/pages/home/Setting.jsx
  frontend/src/pages/home/Users.jsx
Labels: addition

#53 Update backend routes for Admin Dashboard
  backend/server.js
  frontend/src/App.jsx
Labels: change, fix

#55 Splitted DB scripts into multiple files
  backend/scripts/DB.sql
  backend/scripts/DB/Auth.sql
  backend/scripts/DB/DB.sql
  backend/scripts/DB/Feedback.sql
  backend/scripts/DB/Forum.sql
  backend/scripts/DB/Job.sql
  backend/scripts/DB/Payment.sql
  backend/scripts/DB/Profile.sql
  backend/scripts/DB/Technical.sql
  backend/scripts/Sample.sql
  backend/scripts/Sample/Auth.sql
  backend/scripts/Sample/Feedback.sql
  backend/scripts/Sample/Forum.sql
  backend/scripts/Sample/Job.sql
  backend/scripts/Sample/Payment.sql
  backend/scripts/Sample/Profile.sql
  backend/scripts/Sample/Technical.sql
Labels: change

#58 Update DB scripts
  backend/scripts/DB/Auth.sql
  backend/scripts/DB/Forum.sql
  backend/scripts/Sample/Forum.sql
  backend/scripts/Sample/Payment.sql
Labels: addition, change

#59 Update backend: nodejs run script
  backend/package.json
Labels: addition

#63 Forum update
  backend/src/routes/posts.js
  frontend/src/components/buttons/NavigateButton.jsx
  frontend/src/components/forum/AddForm.jsx
  frontend/src/components/forum/EditForm.jsx
  frontend/src/components/forum/ListPost.jsx
  frontend/src/components/forum/Post.jsx
  frontend/src/hooks/usePostUpdate.js
  frontend/src/pages/forum/AddPost.jsx
  frontend/src/pages/forum/EditPost.jsx
  frontend/src/pages/forum/Forum.jsx
  frontend/src/pages/forum/PostDetail.jsx
Labels: addition, change

#64 JobDetail
  backend/package-lock.json
  backend/package.json
  backend/server.js
  backend/src/routes/jobs.js
  frontend/src/assets/css/EnlistJob.css
  frontend/src/hooks/useJobInsert.js
  frontend/src/pages/jobs/EnlistJob.jsx
  frontend/src/pages/jobs/JobDetail.jsx
  frontend/vite.config.js
Labels: addition

#67 Hoàng
  .gitignore
  backend/config/db.json
  backend/scripts/DB.sql
  backend/scripts/SampleDataforJobMarket.sql
  backend/server.js
  backend/src/model/DBContext.js
  backend/src/model/db.js
  backend/src/routes/datapost.js
  backend/src/routes/market.js
  backend/src/routes/marketing.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/css/Carosel.css
  frontend/src/assets/css/Home.css
  frontend/src/assets/css/JobDashboard.css
  frontend/src/assets/css/JobList.css
  frontend/src/assets/css/PriceBar.css
  frontend/src/assets/css/SearchBar.css
  frontend/src/components/HomeNavbar.jsx
  frontend/src/components/TestData.jsx
  frontend/src/components/home/HomeCarousel.jsx
  frontend/src/components/home/HotNew.jsx
  frontend/src/components/job/FilterPrice.jsx
  frontend/src/components/job/JobList.jsx
  frontend/src/components/job/JobPagination.jsx
  frontend/src/components/job/SearchBar.jsx
  frontend/src/hooks/useJobList.js
  frontend/src/hooks/useJobListbyTime.js
  frontend/src/hooks/useJobListbyView.js
  frontend/src/pages/home/HomeGuest.jsx
  frontend/src/pages/home/HomePage.jsx
  frontend/src/pages/jobs/EnlistJob.jsx
  frontend/src/pages/jobs/JobHistory.jsx
  frontend/src/pages/jobs/Market.jsx
  frontend/src/pages/jobs/MyJobs.jsx
Labels: addition, change

#70 Duc
  .github/ISSUE_TEMPLATE/bug_report.md
  backend/config/db.json
  backend/package-lock.json
  backend/package.json
  backend/scripts/DB/Auth.sql
  backend/scripts/DB/Forum.sql
  backend/scripts/Sample/Forum.sql
  backend/scripts/Sample/Payment.sql
  backend/server.js
  backend/src/routes/auth.js
  backend/src/routes/jobs.js
  backend/src/routes/posts.js
  backend/src/routes/ticket.js
  frontend/package-lock.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/css/EnlistJob.css
  frontend/src/components/HomeNavbar.jsx
  frontend/src/components/buttons/NavigateButton.jsx
  frontend/src/components/forum/AddForm.jsx
  frontend/src/components/forum/EditForm.jsx
  frontend/src/components/forum/ListPost.jsx
  frontend/src/components/forum/Post.jsx
  frontend/src/hooks/useCountUser.js
  frontend/src/hooks/useJobInsert.js
  frontend/src/hooks/useLoginQuery.js
  frontend/src/hooks/useMarketContent.js
  frontend/src/hooks/useNewsContent.js
  frontend/src/hooks/usePostDetail.js
  frontend/src/hooks/usePostInsert.js
  frontend/src/hooks/usePostUpdate.js
  frontend/src/hooks/usePostsQuery.js
  frontend/src/hooks/use____Query.js
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/auth/Login.jsx
  frontend/src/pages/auth/Register.jsx
  frontend/src/pages/auth/ResetPassword.jsx
  frontend/src/pages/error/ErrorPage.jsx
  frontend/src/pages/error/error.css
  frontend/src/pages/forum/AddPost.jsx
  frontend/src/pages/forum/EditPost.jsx
  frontend/src/pages/forum/Forum.jsx
  frontend/src/pages/forum/PostDetail.jsx
  frontend/src/pages/home/HomeGuest.jsx
  frontend/src/pages/home/HomePage.jsx
  frontend/src/pages/jobs/EnlistJob.jsx
  frontend/src/pages/jobs/JobDetail.jsx
  frontend/src/pages/profile/Information.jsx
  frontend/src/pages/profile/Profile.jsx
  frontend/src/pages/profile/Security.jsx
  frontend/src/pages/user/CreateTicket.jsx
  frontend/vite.config.js
  node_modules/.package-lock.json
  package-lock.json
Labels: addition, change

#69 Admin dashboard prototype
  backend/config/db.json
  frontend/src/App.jsx
  frontend/src/pages/profile/Profile.jsx
  frontend/src/pages/profile/Security.jsx
Labels: change

#71 Hoàng
  frontend/src/App.jsx
  frontend/src/assets/css/Dashboard.css
  frontend/src/assets/css/JobDashboard.css
  frontend/src/assets/css/Navbar.css
  frontend/src/assets/css/SideBar.css
  frontend/src/components/job/DashBoard.jsx
  frontend/src/components/job/JobList.jsx
  frontend/src/components/job/SideBar.jsx
  frontend/src/pages/jobs/MyJobs.jsx
Labels: change, fix

#72 Forum update
  backend/scripts/DB/Forum.sql
  backend/scripts/Sample/Forum.sql
  backend/server.js
  backend/src/routes/posts.js
  frontend/src/components/buttons/NavigateButton.jsx
  frontend/src/components/forum/AddForm.jsx
  frontend/src/components/forum/EditForm.jsx
  frontend/src/components/forum/ListPost.jsx
  frontend/src/components/forum/Post.jsx
  frontend/src/hooks/forum/usePostDelete.js
  frontend/src/hooks/forum/usePostDetail.js
  frontend/src/hooks/forum/usePostInsert.js
  frontend/src/hooks/forum/usePostUpdate.js
  frontend/src/hooks/forum/usePostsQuery.js
  frontend/src/pages/forum/AddPost.jsx
  frontend/src/pages/forum/EditPost.jsx
Labels: addition, change, fix

#73 JobDetail and update EnlisttJob
  frontend/src/pages/jobs/EnlistJob.jsx
  frontend/src/pages/jobs/JobDetail.jsx
Labels: addition

#74 mJob fix
  backend/package-lock.json
  backend/package.json
  backend/server.js
  backend/src/models/DBContext.js
  backend/src/models/db.js
  backend/src/routes/posts.js
  frontend/src/App.jsx
  frontend/src/components/forum/EditForm.jsx
  frontend/src/components/forum/ListPost.jsx
  frontend/src/components/forum/Post.jsx
  frontend/src/functions/Converter.js
  frontend/src/hooks/forum/usePostUpdate.js
  frontend/src/pages/forum/Forum.jsx
  frontend/src/pages/forum/PostDetail.jsx
  frontend/src/pages/home/HomeGuest.jsx
Labels: fix

#77 Hoàng
  backend/scripts/Sample/JobSampleData/SWPDBScript.sql
  backend/scripts/Sample/JobSampleData/SWPDataJob.sql
Labels: addition, change

#81 EditJob, EnlistJob and JobDetail fixed
  .gitignore
  client/package-lock.json
  client/src/App.jsx
  client/src/assets/css/EditJob.css
  client/src/assets/css/EnlistJob.css
  client/src/hooks/useJobUpdate.js
  client/src/pages/jobs/EditJob.jsx
  client/src/pages/jobs/EnlistJob.jsx
  client/src/pages/jobs/JobDetail.jsx
  server/package-lock.json
  server/src/routes/jobs.js
  start.sh
Labels: change, fix

#82 Recover Security and Profile pages of client
  client/src/App.jsx
Labels: fix

#88 Forum update
  client/package-lock.json
  client/package.json
  client/src/components/Navbar.jsx
  client/src/components/forum/ListPost.jsx
  client/src/components/forum/Post.jsx
  client/src/components/forum/PostCard.jsx
  client/src/components/ui/buttons/NavigateButton.jsx
  client/src/components/ui/buttons/NavigateLink.jsx
  client/src/context/ForumContext.jsx
  client/src/hooks/forum/posts/usePostsQuery.js
  client/src/pages/auth/Login.jsx
  client/src/pages/auth/Logout.jsx
  client/src/pages/forum/AddPost.jsx
  client/src/pages/forum/EditPost.jsx
  client/src/pages/forum/Forum.jsx
  client/src/pages/forum/PostDetail.jsx
  server/src/routes/forum/post/Get.js
Labels: addition, change

#101 Hoang after update
  client/src/hooks/useUserAppliedJobList.js
  client/src/hooks/useUserCompletedJobList.js
  client/src/hooks/useUserTotalCompletedJob.js
Labels: addition, change

#87 Update DB
  server/scripts/DB/Auth.sql
  server/scripts/DB/Feedback.sql
  server/scripts/DB/Forum.sql
  server/scripts/DB/Job.sql
  server/scripts/DB/Payment.sql
  server/scripts/DB/Profile.sql
  server/scripts/DB/Technical.sql
  server/scripts/Sample/Auth.sql
  server/scripts/Versions/June 27.sql
Labels: change, fix

#102 Update Personal Job DashBoard
  client/src/components/job/DashBoard.jsx
  client/src/components/job/SideBar.jsx
  client/src/hooks/useUserTotalCreatedJob.js
  client/src/hooks/useUserTotalCurrentAppliedJob.js
Labels: addition

#104 Forum update
  .gitignore
  client/src/App.css
  client/src/App.jsx
  client/src/assets/css/Forum.css
  client/src/components/Navbar.jsx
  client/src/components/forum/Comment.jsx
  client/src/components/forum/CommentForm.jsx
  client/src/components/forum/ListComment.jsx
  client/src/components/forum/ListPost.jsx
  client/src/components/forum/Post.jsx
  client/src/components/forum/PostCard.jsx
  client/src/components/forum/PostSearch.jsx
  client/src/context/ForumContext.jsx
  client/src/hooks/forum/comments/useCommentDelete.js
  client/src/hooks/forum/comments/useCommentDetail.js
  client/src/hooks/forum/comments/useCommentsQuery.js
  client/src/main.jsx
  client/src/pages/forum/Forum.jsx
  client/src/pages/forum/PostDetail.jsx
  server/package-lock.json
  server/package.json
  server/scripts/Sample/Forum.sql
  server/server.js
  server/src/routes/Forum.js
  server/src/routes/auth.js
  server/src/routes/forum/Comment.js
  server/src/routes/forum/Like.js
  server/src/routes/forum/comment/Get.js
  server/src/routes/forum/comment/Post.js
  server/src/routes/forum/post/Get.js
Labels: addition, change, fix
